# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46cccc9d195adb04aef05ffa558db62a96a012d2d4c5521bb10fec8049f484e51761b8ca9d0b3fadd353b31d157c23270bb181d9b8f6a31fee77a1f9a01bfccd

test:
  secret_key_base: b0139ecd6b1ab1d3d4c9da4a58d13e1a20345dc6dd91ff73160b3768548ad46602f89b6708cad79d5101471c0bc3864bf2beaf32dbfce61f7e8616ab20efda54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
